AWSTemplateFormatVersion: "2010-09-09"
Description: "Database EC2 (MySQL) Stack - Private Subnet (Ubuntu 22.04)"

Resources:

  DatabaseEC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      KeyName: my-first-key
      SubnetId: subnet-04f41508091d1d626   # Private subnet
      SecurityGroupIds:
        - sg-037b824d2b8384fc1
      ImageId: ami-0c7217cdde317cfec       # Ubuntu 22.04 LTS
      Tags:
        - Key: Name
          Value: database-ec2

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /var/log/userdata.log 2>&1
          echo "===== START USERDATA ====="

          echo ">>> Update system"
          apt-get update -y
          apt-get upgrade -y

          echo ">>> Add Ubuntu Universe repo"
          add-apt-repository universe -y
          apt-get update -y

          echo ">>> Install MySQL Server"
          DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server

          echo ">>> Enable MySQL and start service"
          systemctl enable mysql || true
          systemctl start mysql || true

          echo ">>> Configure bind-address"
          sed -i 's/^bind-address.*/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf || true

          echo ">>> Restart MySQL"
          systemctl restart mysql || true

          echo "===== USERDATA COMPLETED ====="

Outputs:
  DatabaseEC2Id:
    Description: "Instance ID of the database EC2"
    Value: !Ref DatabaseEC2

  DatabasePrivateIP:
    Description: "Private IP of the database EC2"
    Value: !GetAtt DatabaseEC2.PrivateIp
