AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for monitoring WebApp EC2 with SNS alerts and CloudWatch dashboard

Parameters:
  WebAppInstanceId:
    Type: String
    Description: EC2 Instance ID of your WebApp

Resources:

  # SNS Topic for alerts
  AlertSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: WebAppAlerts

  # SNS Email Subscription
  AlertEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      Endpoint: anasdev8@gmail.com  # Replace with your email
      TopicArn: !Ref AlertSNSTopic

  # CloudWatch Alarm for high CPU usage
  WebAppHighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: WebAppHighCPU
      AlarmDescription: "Triggered if CPU exceeds 80%"
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Dimensions:
        - Name: InstanceId
          Value: !Ref WebAppInstanceId
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlertSNSTopic
      TreatMissingData: notBreaching

  # CloudWatch Dashboard
  WebAppDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: WebAppDashboard
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 6,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "AWS/EC2", "CPUUtilization", "InstanceId", "${WebAppInstanceId}" ]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "CPU Utilization"
              }
            }
          ]
        }

Outputs:
  SNSTopicArn:
    Description: "ARN of the SNS Topic"
    Value: !Ref AlertSNSTopic

  HighCPUAlarmName:
    Description: "Name of the CloudWatch Alarm"
    Value: !Ref WebAppHighCPUAlarm

  DashboardName:
    Description: "Name of the CloudWatch Dashboard"
    Value: !Ref WebAppDashboard
